default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: marcio
  password: 123

development:
  <<: *default
  database: ieat_development

test:
  <<: *default
  database: ieat_test

production:
  <<: *default
  database: ieat_production
  username: ieat
  password: <%= ENV['IEAT_DATABASE_PASSWORD'] %>
